### ISSUE TITLE
Exception: unknown tag: ColWidth

### ISSUE THREAD

**Issue by ngirard** [entangled/filters#13]
Apologizes if I'm reporting in the wrong repository.

When following your [tutorial](https://entangled.github.io/tutorial.html), and after installing everything properly, I stumbled upon this error:
```sh
make site
pandoc --template style/template.html --css css/bootstrap.css --css css/mods.css -t html5 -s --mathjax --toc --toc-depth 1 --filter pandoc-bootstrap -f markdown+multiline_tables+simple_tables lit/index.md -o docs/index.html
Traceback (most recent call last):
  File "/home/ngirard/.local/bin/pandoc-bootstrap", line 8, in <module>
    sys.exit(main())
  File "/home/ngirard/.local/lib/python3.8/site-packages/entangled/bootstrap.py", line 160, in main
    run_filters([bootstrap_card_deck, bootstrap_fold_code], prepare=prepare, doc=doc)
  File "/home/ngirard/.local/lib/python3.8/site-packages/panflute/io.py", line 233, in run_filters
    doc = load(input_stream=input_stream)
  File "/home/ngirard/.local/lib/python3.8/site-packages/panflute/io.py", line 56, in load
    doc = json.load(input_stream, object_pairs_hook=from_json)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/home/ngirard/.local/lib/python3.8/site-packages/panflute/elements.py", line 1478, in from_json
    raise Exception('unknown tag: ' + tag)
Exception: unknown tag: ColWidth
Error running filter pandoc-bootstrap:
Filter returned error status 1
make: *** [Makefile:53 : docs/index.html] Erreur 83
```

Any ideas ?

Cheers

**Comment by jhidding** [comment]
Thanks for this report! I will look into it.

**Comment by ngirard** [comment]
As far as I understand, this is due to an API change in Pandoc, with which the Panflute version that entangled-filters currently depends on is incompatible.
I'd suggest upgrading Panflute's version in entangled-filters' dependancies.

FWIW, upgrading Panflute version solved the problem on my system.

**References:**
- [Supporting pandoc 2.11 · Issue #142 · sergiocorreia/panflute](https://github.com/sergiocorreia/panflute/issues/142)
- my own console output when trying to upgrade Panflute:
```sh
pip3 install --user --upgrade panflute
Collecting panflute
  Downloading panflute-2.0.5.tar.gz (33 kB)
Requirement already satisfied, skipping upgrade: click in /usr/lib/python3/dist-packages (from panflute) (7.0)
Requirement already satisfied, skipping upgrade: pyyaml in /usr/lib/python3/dist-packages (from panflute) (5.3.1)
Building wheels for collected packages: panflute
  Building wheel for panflute (setup.py) ... done
  Created wheel for panflute: filename=panflute-2.0.5-py3-none-any.whl size=34292 sha256=0da8eaf20bc8bbca79d6bd9d7d9d40f5900fd2d7fb218c1011ce28fe506db2cd
  Stored in directory: /home/ngirard/.cache/pip/wheels/10/4a/fe/74791846d401c21ee1fb7c4b99c07d67099701645ef531b37a
Successfully built panflute
ERROR: entangled-filters 0.8.0 has requirement panflute==1.11.2, but you'll have panflute 2.0.5 which is incompatible.
Installing collected packages: panflute
  Attempting uninstall: panflute
    Found existing installation: panflute 1.11.2
    Uninstalling panflute-1.11.2:
      Successfully uninstalled panflute-1.11.2
Successfully installed panflute-2.0.5
```

**Comment by numero-744** [comment]
Hello, any updates about this?

Related issue: https://github.com/entangled/entangled/issues/110
